### ISSUE TITLE
LaTeX.format. Braces for degree

### ISSUE THREAD

**Issue by FoggyFinder** [mathnet/mathnet-symbolics#10]
I think in the output string in LaTeX format should be curly brackets ({ }) in the degree .

Example:

```
"x^(4+sin(x))"
|> Infix.parseOrUndefined
|> LaTeX.format
|> printfn "%s"
```

Print:
`
x^\left(4 + \sin{x}\right)`

Display:

![0](https://cloud.githubusercontent.com/assets/16510738/14040754/f39c8690-f283-11e5-8428-d02c57007b5a.png)

I think there should be this string:

`x^{\left(4 + \sin{x}\right)}`

Display:

![1](https://cloud.githubusercontent.com/assets/16510738/14040810/5216070a-f284-11e5-81fb-6ac7304bce02.png)

**Comment by cdrnet** [comment]
Yes, that would be much better, thanks!

**Comment by cdrnet** [comment]
Would we still want to keep the parentheses?

**Comment by FoggyFinder** [comment]
I agree - they are redundant

**Comment by cdrnet** [comment]
Yes, let's drop them in this case (controlled by priorities).

So we'd expect parenthesis for `(x^y)^z`, but not for `x^(y^z)`?

Would be great to have some more test cases for the unit tests in this area.

**Comment by FoggyFinder** [comment]
A matter of taste, I like both version:

![0](https://cloud.githubusercontent.com/assets/16510738/14043892/eefef05e-f2a2-11e5-8a9b-27d40f606e8c.png)

**Comment by cdrnet** [comment]
I've changed the logic to emit braces rather aggressively, which should resolve this. The parenthesis are as before. Thanks again for reporting this.
