### ISSUE TITLE
Parse errors in c#

### ISSUE THREAD

**Issue by qoptics** [mathnet/mathnet-symbolics#17]
Thanks for the excellent package.  When I use the C# example code, most parsing works fine.  However, parsing sqrt(x), sinh(x), cosh(x), and tanh(x) all throw parsing errors.  Other function, such as sin(x), cos(x), tan(x) all parse fine.

**Comment by cdrnet** [comment]
This is with version 0.9?

**Comment by FoggyFinder** [comment]
With regard to *sqrt* the reason is that it is not specified as a function, therefore, when parsing, returns *Undefined*. I think makes sense when parsing to replace it on Expression.Power.

**Comment by cdrnet** [comment]
Yes, this area definitely needs some work and design, also related to #8.

**Comment by FoggyFinder** [comment]
A very interesting topic. There's definitely something to think about. But I guess it makes sense to correct this inaccuracy with a `sqrt` in the current implementation. I can try to fix it in the next few days.

**Comment by qoptics** [comment]
Thanks for looking into this.  Yes, I am using version 0.9.

**Comment by FoggyFinder** [comment]
@qoptics Now it should work. Although now you need to build the library from source.

**Comment by cdrnet** [comment]
Released as v0.10. Thanks again.
