### ISSUE TITLE
Evaluate in C#

### ISSUE THREAD

**Issue by qoptics** [mathnet/mathnet-symbolics#19]
Thank you for changing it to allow sqrt, etc.  I just switched from 0.9 to 1.0 to test this, and I can't get the "Evaluate.Evaluate()" function to work in C#.  This function previously accepted two arguments (symbols, expression), but now it seems to accept just one argument (symbols).  I'm not familiar with f#, so it is hard to tell how to provide the expression argument to the evaluate function.

Thanks.

**Comment by cdrnet** [comment]
The arguments of Evaluate should not have changed - let me check this.

**Comment by cdrnet** [comment]
The change was indeed not intended - I'll release a patch version 0.10.1 to fix the API.

**Comment by cdrnet** [comment]
Fixed in v0.10.1. Thanks for reporting this!
