### ISSUE TITLE
Building on Mono 3.12.0 

### ISSUE THREAD

**Issue by Hokua** [mathnet/mathnet-symbolics#2]
Unable to build on Mono 3.12, get F# errors FS0001 insdie the Trignonometic module

**Comment by cdrnet** [comment]
Oh, are there official mono 3.12 binaries somewhere or did you compile mono from source?

**Comment by Hokua** [comment]
That version of Mono is in the Xamarin Studio alpha channel. I can try with Mono 3.10.

**Comment by cdrnet** [comment]
I can reproduce with xamarin's own debian packages for mono 3.10 (on ubuntu via vagrant)

**Comment by cdrnet** [comment]
Quite weird, it does not seem to find the overloaded `*` Expression operators. Need to check with an even older version of mono to rule out a mono regression (if I remember correctly I did test successfully with mono 3.2.8 some time ago). All is fine on .Net.

**Comment by Hokua** [comment]
Yes I was able to add Sqrt as a recognized function by the parser and compile in Visual Studio community and copy the DLL over to my Mac. Im new to F#, so was unable to figure out the bug. Thanks for checking into it!

**Comment by cdrnet** [comment]
Confirmed to work fine when compiled against Mono4 (verified with travis CI).
