### ISSUE TITLE
Support for function Ctg is missing

### ISSUE THREAD

**Issue by FoggyFinder** [mathnet/mathnet-symbolics#24]
It seems that support for function `Ctg` is missing. I think it makes sense to add it. I can do it, but I would like to know which option is better:

1. Replacing the function by `tg` when parsing (so, add `ctg` to the class Pseudo)
2. Implement full support

**Comment by cdrnet** [comment]
I don't think I've heard about `ctg` and `tg` functions. What are these about?

**Comment by FoggyFinder** [comment]
@cdrnet sorry, I meant
`ctg` - cotangents 
`tg` - tangents

**Comment by cdrnet** [comment]
Ah, right. In Numerics we refer to them as `tan` and `cot`. Maybe there are different naming schemes?

Of course, I'm fine with adding them. If we add `cot` (or `ctg`), we may want to add `sec` and `csc` as well to get the full set (`cot=1/tan`, `sec=1/cos`, `csc=1/sin`).

**Comment by cdrnet** [comment]
So the remaining question is whether they shall be full expressions or just infix parsing magic. I'd vote to implement them fully and then maybe provide a routine later that simplifies all of them to `sin` and `cos`.

**Comment by FoggyFinder** [comment]
Next week, I'll think how can expand the module `Trigonometric`, so  I will leave the issue open

**Comment by FoggyFinder** [comment]
https://github.com/mathnet/mathnet-symbolics/pull/46
