### ISSUE TITLE
Implicit Operator in Expression

### ISSUE THREAD

**Issue by FoggyFinder** [mathnet/mathnet-symbolics#26]
Is there a need for the existence of the Implicit Operator for string in Expression?

https://github.com/mathnet/mathnet-symbolics/blob/96a21c9c2413a080daff7dc3943a22f8b80179b3/src/Symbolics/Expression.fs#L485

As this may lead to weird results

For example:
```csharp
            string example = "1a/)";
            Expression test = example;
            Console.WriteLine(Infix.Format(test)); // => 1a/)
            Console.WriteLine(LaTeX.Format(test)); // => {1a/)}
```

**Comment by cdrnet** [comment]
I understand why I added it, but in retrospect I agree that it was a bad idea.
