### ISSUE TITLE
Handling expressions with floating point coefficients with inFix.Parse

### ISSUE THREAD

**Issue by shyamupa** [mathnet/mathnet-symbolics#3]
This issue originated from [this](http://stackoverflow.com/questions/31252695/parse-expression-with-double-coefficient-values-in-mathdotnet/31254389#31254389) question.

The `InFix.Parse` method should support handling of cases like

`Infix.ParseOrThrow("1.5*apples + oranges");`

**Comment by cdrnet** [comment]
Implemented in master, together with another fix to allow spaces after numbers.
