### ISSUE TITLE
Format->Parse of Infix-Expression fails

### ISSUE THREAD

**Issue by patham9** [mathnet/mathnet-symbolics#30]
Infix.parse has troubles parsing the E-notation Infix.Format (and also FormatStrict) generates:
```
2*soll_14_0_0 + 0.05*soll_14_1_0 + (-6)*x_0_0_0 + (-6.40869140625E-05)*x_0_1_0                                                                  
                                                                 ^Expecting: infix operator or ')'
```
So the issue is that it is currently not possible to format and then re-parse infix expressions.

Is there a faster or at least different way to serialize expressions to workaround the issue in the meanwhile?

Best regards,
Patricck

**Comment by patham9** [comment]
A dirty hack solution I used for now:

```
| Approximation (Approximation.Real fp) ->
            if fp >= 0.0 then write (fp.ToString("0.#########").Replace(".","§"))
            else
                if priority > 0 then write "("
                write (fp.ToString("0.#########").Replace(".","§"));
                if priority > 0 then write ")"
```

On the other side then $ has to be replaced back to . again of course.

This shows one way to deal with this issue, namely to force it to not use the exponential notation. However this often results in much longer string lengths, so I guess a change in the parser that takes into account the format of the Invariant culture will be necessary in the end.

Best regards,
Patrick

**Comment by cdrnet** [comment]
Thanks for reporting this. Yes, format and strict are supposed to be symmetric (expect for some loss of precision when using approximations - but that's ok since they are approximations after all).

**Comment by cdrnet** [comment]
(slightly related: #29)

**Comment by patham9** [comment]
Indeed, this is elegant and also fixes it. Thank you!

**Comment by cdrnet** [comment]
This seems to be fixed now in master and the next release. Thanks!
