### ISSUE TITLE
Necessity of the module NumericLiteralQ

### ISSUE THREAD

**Issue by FoggyFinder** [mathnet/mathnet-symbolics#51]
I'm not sure in target of the module [`NumericLiteralQ`](https://github.com/mathnet/mathnet-symbolics/blob/f03a6c71e851ec583ce74f7ff89440744481fd77/src/Symbolics/Expression.fs#L594-L599).

The four from five functions is duplicate from the module [`Operators`](https://github.com/mathnet/mathnet-symbolics/blob/f03a6c71e851ec583ce74f7ff89440744481fd77/src/Symbolics/Expression.fs#L130)

The last one function `FromString` is simple, so maybe better just remove this module?

**Comment by cdrnet** [comment]
The point of this module is to allow the `4Q` notation directly in F# source code (F# compiler conventions). The module is not intended to be used by other means.

**Comment by FoggyFinder** [comment]
Oh, really - I had to check before creating issue...

**Comment by cdrnet** [comment]
I guess a code comment at that module explaining its purpose would not be wrong, especially since it involves "compiler magic" :)
