### ISSUE TITLE
.Net Core / .Net Standard 2.0

### ISSUE THREAD

**Issue by kraptor23** [mathnet/mathnet-symbolics#55]
Any plans to support .Net Core / Standard? I would love to use this library in my core application (MathNet Numerics in use already).

**Comment by cdrnet** [comment]
Yes, my plan is to support .Net Standard 2.0 for all Math.NET projects. But so far I've postponed any investments until Numerics v4 is released, so we can reuse its tooling which has by then proven to work well.

**Comment by kraptor23** [comment]
Thanks for the update - I look forward to v4!

**Comment by kraptor23** [comment]
Just checking in on this - MathNet Numerics is awesome - any progress on migrating the other projects - especially Symbolics?

**Comment by AdaskoTheBeAsT** [comment]
I keep my fingers crossed for .NET Standard version :)

**Comment by cdrnet** [comment]
Math.NET Symbolics v0.19 and newer support .Net Standard 2.0.

**Comment by diluculo** [comment]
@cdrnet, `paket.bootstrapper.exe` has been renamed, but `restore.cmd` and `restore.sh` have not yet changed. Please update them.

**Comment by diluculo** [comment]
One more, no tests are shown in the Test Explorer again.

Build.cmd is working fine. In VS 2017, building itself is OK, but there are errors in the Tests and Package Manager output pane.

Tests Output Pane:
```
[2018-10-29 PM 5:15:57 Informational] ------ Discover test started ------
[2018-10-29 PM 5:15:58 Error] System.InvalidOperationException: The operation failed as details for project Symbolics could not be loaded.
   at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAsync(DependencyGraphCacheContext context)
   at NuGet.VisualStudio.VsPackageInstallerServices.<GetPackagesPathResolverAsync>d__8.MoveNext()
...
```

Package Manager Output Pane:

```
Error occurred while restoring NuGet packages: The operation failed as details for project Symbolics could not be loaded.
```

I installed the latest dotnet cli from [here](https://github.com/dotnet/core/blob/master/release-notes/2.2/preview/2.2.0-preview3-download.md).

**Comment by cdrnet** [comment]
Thanks for the hints. I've fixed the first two, but I don't think we can get the VS Test Explorer to work easily again (due to limitations of the VS adapter).
