### ISSUE TITLE
Does library work in C++/CLI projects? 

### ISSUE THREAD

**Issue by FoggyFinder** [mathnet/mathnet-symbolics#59]

**Comment by cdrnet** [comment]
I have never tried - but am not aware of anything that would obviously cause a problem.

**Comment by FoggyFinder** [comment]
I heard from someone that he wasn't able to use this library. It was a couple months ago. I didn't test it by myself as I was busy. Now I checked it with examples from the docs. Works great.

Probably he stuck with references to the dll-s or forgot to set `true` for  `AutoGenerateBindingRedirects`.
