### ISSUE TITLE
Parsing constants as identifiers

### ISSUE THREAD

**Issue by Zaid-Ajaj** [mathnet/mathnet-symbolics#6]
Right now the expression `Infix.parse "pi"` returns `ParsedResult` of an identifier (i.e. `symbol "pi"`) .
updating the `identifier` parser solves this problem

    let identifier : Expression parser =
        let isIdentifierFirstChar c = isLetter c
        let isIdentifierChar c = isLetter c || isDigit c
        many1Satisfy2L isIdentifierFirstChar isIdentifierChar "identifier" .>> ws
        |>> function // differentating between constants and identifiers
            | "pi"  -> Expression.Constant Pi
            | "e" -> Expression.Constant E
            | "oo" | "inf" -> Expression.Constant PositiveInfinity // 'oo' from sympy
            | "j" -> Expression.Constant I
            | id -> Expression.Symbol id
now it works:

    Infix.parse "pi" 
    // val it : ParseResult = ParsedExpression π

**Comment by cdrnet** [comment]
Thanks - this has already been merged (since it was pushed to the same branch of the pull request #5).
