### ISSUE TITLE
Sample of usage with C++/CLI & VB.NET 

### ISSUE THREAD

**Issue by FoggyFinder** [mathnet/mathnet-symbolics#60]
Maybe it makes sense to expand section ["Math.NET Symbolics with C#"](https://symbolics.mathdotnet.com/#Math-NET-Symbolics-with-C) in documentation with example with VB.NET, C++/CLI ?

**Comment by cdrnet** [comment]
Absolutely. And we should also update it to use the `SymbolicExpression` facade which is much easier to use in C# (likely also VB.NET and C++/CLI).
