### ISSUE TITLE
What about cooperation?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [mathnet/mathnet-symbolics#87]
Hello!
I'm WhiteBlackGoose, author of a new symbolic algebra library [AngouriMath](https://github.com/asc-community/AngouriMath).

I thought that we could somehow cooperate, maybe integrate some common API between Math.NET's libraries and AngouriMath.

Feel free to redirect me to some channel on slack/discord/gitter anywhere else where we can discuss it, if you find it interesting enough (discussing it in here might be not very efficient).

**Comment by cdrnet** [comment]
Hi

Sure, I'm open to discuss any form of cooperation. Aligning on some APIs or some way to interoperate would certainly be interesting. Even if only, for example, to be able to easily validate/test e.g. Symbolics algorithms against AngouriMath.

**Comment by WhiteBlackGoose** [comment]
I think it'd be better to have a discussion in a chat, to be honest (otherwise it'd go too slow). If you have discord, I'm Oryp4ik#0120

**Comment by WhiteBlackGoose** [comment]
So, no reaction. Ok.
